--------------------------------------------------------
-- Archivo creado  - miércoles-junio-04-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DETALLEPEDIDO
--------------------------------------------------------

  CREATE TABLE "CHEDYS"."DETALLEPEDIDO" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"PEDIDO_ID" VARCHAR2(3 BYTE), 
	"ALIMENTO_ID" NUMBER, 
	"PRECIO" FLOAT(53)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into CHEDYS.DETALLEPEDIDO
SET DEFINE OFF;
Insert into CHEDYS.DETALLEPEDIDO (ID,PEDIDO_ID,ALIMENTO_ID,PRECIO) values (41,'013',25,55);
Insert into CHEDYS.DETALLEPEDIDO (ID,PEDIDO_ID,ALIMENTO_ID,PRECIO) values (42,'013',1,55);
Insert into CHEDYS.DETALLEPEDIDO (ID,PEDIDO_ID,ALIMENTO_ID,PRECIO) values (43,'013',4,20);
Insert into CHEDYS.DETALLEPEDIDO (ID,PEDIDO_ID,ALIMENTO_ID,PRECIO) values (1,'001',1,55);
Insert into CHEDYS.DETALLEPEDIDO (ID,PEDIDO_ID,ALIMENTO_ID,PRECIO) values (2,'002',1,55);
Insert into CHEDYS.DETALLEPEDIDO (ID,PEDIDO_ID,ALIMENTO_ID,PRECIO) values (36,'013',1,55);
Insert into CHEDYS.DETALLEPEDIDO (ID,PEDIDO_ID,ALIMENTO_ID,PRECIO) values (8,'005',7,22);
Insert into CHEDYS.DETALLEPEDIDO (ID,PEDIDO_ID,ALIMENTO_ID,PRECIO) values (11,'007',4,20);
Insert into CHEDYS.DETALLEPEDIDO (ID,PEDIDO_ID,ALIMENTO_ID,PRECIO) values (15,'004',5,25);
Insert into CHEDYS.DETALLEPEDIDO (ID,PEDIDO_ID,ALIMENTO_ID,PRECIO) values (39,'013',4,20);
Insert into CHEDYS.DETALLEPEDIDO (ID,PEDIDO_ID,ALIMENTO_ID,PRECIO) values (44,'013',23,120);
Insert into CHEDYS.DETALLEPEDIDO (ID,PEDIDO_ID,ALIMENTO_ID,PRECIO) values (22,'008',3,38);
Insert into CHEDYS.DETALLEPEDIDO (ID,PEDIDO_ID,ALIMENTO_ID,PRECIO) values (25,'010',4,20);
Insert into CHEDYS.DETALLEPEDIDO (ID,PEDIDO_ID,ALIMENTO_ID,PRECIO) values (37,'013',1,55);
Insert into CHEDYS.DETALLEPEDIDO (ID,PEDIDO_ID,ALIMENTO_ID,PRECIO) values (45,'013',1,55);
Insert into CHEDYS.DETALLEPEDIDO (ID,PEDIDO_ID,ALIMENTO_ID,PRECIO) values (47,'014',1,55);
Insert into CHEDYS.DETALLEPEDIDO (ID,PEDIDO_ID,ALIMENTO_ID,PRECIO) values (48,'014',1,55);
Insert into CHEDYS.DETALLEPEDIDO (ID,PEDIDO_ID,ALIMENTO_ID,PRECIO) values (52,'016',4,20);
Insert into CHEDYS.DETALLEPEDIDO (ID,PEDIDO_ID,ALIMENTO_ID,PRECIO) values (9,'006',4,20);
Insert into CHEDYS.DETALLEPEDIDO (ID,PEDIDO_ID,ALIMENTO_ID,PRECIO) values (10,'007',1,55);
Insert into CHEDYS.DETALLEPEDIDO (ID,PEDIDO_ID,ALIMENTO_ID,PRECIO) values (21,'009',5,25);
Insert into CHEDYS.DETALLEPEDIDO (ID,PEDIDO_ID,ALIMENTO_ID,PRECIO) values (23,'008',3,38);
Insert into CHEDYS.DETALLEPEDIDO (ID,PEDIDO_ID,ALIMENTO_ID,PRECIO) values (14,'004',28,25);
Insert into CHEDYS.DETALLEPEDIDO (ID,PEDIDO_ID,ALIMENTO_ID,PRECIO) values (16,'004',26,15);
Insert into CHEDYS.DETALLEPEDIDO (ID,PEDIDO_ID,ALIMENTO_ID,PRECIO) values (24,'010',1,55);
Insert into CHEDYS.DETALLEPEDIDO (ID,PEDIDO_ID,ALIMENTO_ID,PRECIO) values (54,'015',4,20);
Insert into CHEDYS.DETALLEPEDIDO (ID,PEDIDO_ID,ALIMENTO_ID,PRECIO) values (28,'012',21,70);
Insert into CHEDYS.DETALLEPEDIDO (ID,PEDIDO_ID,ALIMENTO_ID,PRECIO) values (38,'013',21,70);
Insert into CHEDYS.DETALLEPEDIDO (ID,PEDIDO_ID,ALIMENTO_ID,PRECIO) values (51,'016',25,55);
Insert into CHEDYS.DETALLEPEDIDO (ID,PEDIDO_ID,ALIMENTO_ID,PRECIO) values (40,'013',1,55);
Insert into CHEDYS.DETALLEPEDIDO (ID,PEDIDO_ID,ALIMENTO_ID,PRECIO) values (53,'015',23,120);
Insert into CHEDYS.DETALLEPEDIDO (ID,PEDIDO_ID,ALIMENTO_ID,PRECIO) values (59,'017',5,25);
Insert into CHEDYS.DETALLEPEDIDO (ID,PEDIDO_ID,ALIMENTO_ID,PRECIO) values (57,'017',1,55);
Insert into CHEDYS.DETALLEPEDIDO (ID,PEDIDO_ID,ALIMENTO_ID,PRECIO) values (58,'017',4,20);
Insert into CHEDYS.DETALLEPEDIDO (ID,PEDIDO_ID,ALIMENTO_ID,PRECIO) values (3,'002',4,20);
Insert into CHEDYS.DETALLEPEDIDO (ID,PEDIDO_ID,ALIMENTO_ID,PRECIO) values (7,'005',1,55);
--------------------------------------------------------
--  DDL for Index SYS_C007506
--------------------------------------------------------

  CREATE UNIQUE INDEX "CHEDYS"."SYS_C007506" ON "CHEDYS"."DETALLEPEDIDO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table DETALLEPEDIDO
--------------------------------------------------------

  ALTER TABLE "CHEDYS"."DETALLEPEDIDO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "CHEDYS"."DETALLEPEDIDO" MODIFY ("PRECIO" NOT NULL ENABLE);
  ALTER TABLE "CHEDYS"."DETALLEPEDIDO" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DETALLEPEDIDO
--------------------------------------------------------

  ALTER TABLE "CHEDYS"."DETALLEPEDIDO" ADD FOREIGN KEY ("PEDIDO_ID")
	  REFERENCES "CHEDYS"."PEDIDOS" ("ID") ENABLE;
  ALTER TABLE "CHEDYS"."DETALLEPEDIDO" ADD FOREIGN KEY ("ALIMENTO_ID")
	  REFERENCES "CHEDYS"."ALIMENTOS" ("ID") ENABLE;
