--------------------------------------------------------
-- Archivo creado  - miércoles-junio-04-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MESAS
--------------------------------------------------------

  CREATE TABLE "CHEDYS"."MESAS" 
   (	"NUMERO" VARCHAR2(3 BYTE), 
	"CAPACIDAD" NUMBER, 
	"UBICACION" VARCHAR2(100 BYTE), 
	"ESTADO" VARCHAR2(20 BYTE) DEFAULT 'Disponible'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into CHEDYS.MESAS
SET DEFINE OFF;
Insert into CHEDYS.MESAS (NUMERO,CAPACIDAD,UBICACION,ESTADO) values ('003',6,'Zona Norte','Ocupado');
Insert into CHEDYS.MESAS (NUMERO,CAPACIDAD,UBICACION,ESTADO) values ('004',7,'Zona Sur','Desocupado');
Insert into CHEDYS.MESAS (NUMERO,CAPACIDAD,UBICACION,ESTADO) values ('001',3,'Zona Oeste','Desocupado');
Insert into CHEDYS.MESAS (NUMERO,CAPACIDAD,UBICACION,ESTADO) values ('005',11,'Zona Centro','Desocupado');
Insert into CHEDYS.MESAS (NUMERO,CAPACIDAD,UBICACION,ESTADO) values ('006',5,'Zona Centro','Desocupado');
Insert into CHEDYS.MESAS (NUMERO,CAPACIDAD,UBICACION,ESTADO) values ('007',4,'Zona Norte','Desocupado');
Insert into CHEDYS.MESAS (NUMERO,CAPACIDAD,UBICACION,ESTADO) values ('011',11,'Zona Sur','Desocupado');
Insert into CHEDYS.MESAS (NUMERO,CAPACIDAD,UBICACION,ESTADO) values ('009',5,'Zona Este','Desocupado');
Insert into CHEDYS.MESAS (NUMERO,CAPACIDAD,UBICACION,ESTADO) values ('010',8,'Zona Sur','Desocupado');
Insert into CHEDYS.MESAS (NUMERO,CAPACIDAD,UBICACION,ESTADO) values ('012',5,'Zona Este','Desocupado');
Insert into CHEDYS.MESAS (NUMERO,CAPACIDAD,UBICACION,ESTADO) values ('008',2,'Zona Este','Desocupado');
--------------------------------------------------------
--  DDL for Index SYS_C007493
--------------------------------------------------------

  CREATE UNIQUE INDEX "CHEDYS"."SYS_C007493" ON "CHEDYS"."MESAS" ("NUMERO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table MESAS
--------------------------------------------------------

  ALTER TABLE "CHEDYS"."MESAS" MODIFY ("CAPACIDAD" NOT NULL ENABLE);
  ALTER TABLE "CHEDYS"."MESAS" ADD CONSTRAINT "CHK_ESTADO_MESAS" CHECK (ESTADO IN ('Desocupado', 'Reservado', 'Ocupado')) ENABLE;
  ALTER TABLE "CHEDYS"."MESAS" ADD PRIMARY KEY ("NUMERO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
