--------------------------------------------------------
-- Archivo creado  - miércoles-junio-04-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MESEROS
--------------------------------------------------------

  CREATE TABLE "CHEDYS"."MESEROS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"PATERNO" VARCHAR2(50 BYTE), 
	"MATERNO" VARCHAR2(50 BYTE), 
	"EDAD" NUMBER, 
	"SEXO" VARCHAR2(10 BYTE), 
	"RFC" VARCHAR2(13 BYTE), 
	"TELEFONO" VARCHAR2(10 BYTE), 
	"CORREO" VARCHAR2(100 BYTE), 
	"DIRECCION" VARCHAR2(200 BYTE), 
	"HORARIO" VARCHAR2(100 BYTE), 
	"USUARIO" VARCHAR2(50 BYTE), 
	"CONTRASENA" VARCHAR2(50 BYTE), 
	"ROL" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into CHEDYS.MESEROS
SET DEFINE OFF;
Insert into CHEDYS.MESEROS (ID,NOMBRE,PATERNO,MATERNO,EDAD,SEXO,RFC,TELEFONO,CORREO,DIRECCION,HORARIO,USUARIO,CONTRASENA,ROL) values (1,'Edith Esmeralda','Perez','Martinez',22,'Femenino','PEME123456789','9514614146','ep9725@gmail.com','Lirios #13','Lunes a Viernes 8 am - 4 pm','Edith123','E123456E','Gerente');
Insert into CHEDYS.MESEROS (ID,NOMBRE,PATERNO,MATERNO,EDAD,SEXO,RFC,TELEFONO,CORREO,DIRECCION,HORARIO,USUARIO,CONTRASENA,ROL) values (2,'Cristian Eduardo','Mendoza','Ramirez',22,'Masculino','MERC123456789','9513311417','mcristianeduardo737@gmail.com','Reforma #1','Sabado a Domingo 8 am - 9 pm','Cristian123','C123456C','Gerente');
Insert into CHEDYS.MESEROS (ID,NOMBRE,PATERNO,MATERNO,EDAD,SEXO,RFC,TELEFONO,CORREO,DIRECCION,HORARIO,USUARIO,CONTRASENA,ROL) values (4,'Eduarda','Ramirez','Martinez',22,'Femenino','RAME123456789','9514614140','mexicanmixes6@gmail.com','Lirios #17','Lunes a Viernes 8 am - 4 pm','Eduarda123','E123456F','Mesero');
Insert into CHEDYS.MESEROS (ID,NOMBRE,PATERNO,MATERNO,EDAD,SEXO,RFC,TELEFONO,CORREO,DIRECCION,HORARIO,USUARIO,CONTRASENA,ROL) values (7,'Esmeralda','Perez','Perez',33,'Femenino','PEPE123456789','9513452520','chedyrs2116@gmail.com','Monte Alban #34','Lunes a Viernes 1 pm - 9 pm','Esmeralda123','E654321E','Gerente');
Insert into CHEDYS.MESEROS (ID,NOMBRE,PATERNO,MATERNO,EDAD,SEXO,RFC,TELEFONO,CORREO,DIRECCION,HORARIO,USUARIO,CONTRASENA,ROL) values (8,'Erick Eduardo','Gomez','Velazco',25,'Masculino','GOVE123456789','9513311410','edithchedy@gmail.com','Reforma #12','Sabado a Domingo 8 am - 9 pm','Erick123','C123456D','Mesero');
Insert into CHEDYS.MESEROS (ID,NOMBRE,PATERNO,MATERNO,EDAD,SEXO,RFC,TELEFONO,CORREO,DIRECCION,HORARIO,USUARIO,CONTRASENA,ROL) values (9,'Edgar Edmundo','Sanchez','Perez',35,'Masculino','SAPE123456789','9513452529','chedy2116ro@gmail.com','Monte Alban #33','Lunes a Viernes 1 pm - 9 pm','Edgar124','E654321F','Mesero');
Insert into CHEDYS.MESEROS (ID,NOMBRE,PATERNO,MATERNO,EDAD,SEXO,RFC,TELEFONO,CORREO,DIRECCION,HORARIO,USUARIO,CONTRASENA,ROL) values (21,'Diego Angel','Perez','Jimenez',34,'Masculino','PEDJ123456789','9513452627','diegito@gmail.com','Pancho Villa #32','Lunes a Viernes 8 am - 4 pm','Diego123','D123456D','Mesero');
Insert into CHEDYS.MESEROS (ID,NOMBRE,PATERNO,MATERNO,EDAD,SEXO,RFC,TELEFONO,CORREO,DIRECCION,HORARIO,USUARIO,CONTRASENA,ROL) values (23,'Guillermo','Lopez','Cortes',67,'Masculino','LOGC123456789','1234567890','guillermito@gmail.com','Calzada guerrero #23','Lunes a Viernes 8 am - 4 pm','Guillermo123','G123456G','Mesero');
Insert into CHEDYS.MESEROS (ID,NOMBRE,PATERNO,MATERNO,EDAD,SEXO,RFC,TELEFONO,CORREO,DIRECCION,HORARIO,USUARIO,CONTRASENA,ROL) values (22,'Natalia ','Jimenez','Ramirez',29,'Femenino','JIRN123456789','9512345676','nati@gmail.com','Calz. I Madero #23','Lunes a Viernes 8 am - 4 pm','Natalia123','N123456N','Gerente');
Insert into CHEDYS.MESEROS (ID,NOMBRE,PATERNO,MATERNO,EDAD,SEXO,RFC,TELEFONO,CORREO,DIRECCION,HORARIO,USUARIO,CONTRASENA,ROL) values (24,'Perla','Lopez','Torres',23,'Femenino','LOPT123456789','9513453434','perla123@gmail.com','Av. Flores #12','Lunes a Viernes 8 am - 4 pm','Perla123','M1c2a3e4','Mesero');
--------------------------------------------------------
--  DDL for Index SYS_C007488
--------------------------------------------------------

  CREATE UNIQUE INDEX "CHEDYS"."SYS_C007488" ON "CHEDYS"."MESEROS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007489
--------------------------------------------------------

  CREATE UNIQUE INDEX "CHEDYS"."SYS_C007489" ON "CHEDYS"."MESEROS" ("RFC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007490
--------------------------------------------------------

  CREATE UNIQUE INDEX "CHEDYS"."SYS_C007490" ON "CHEDYS"."MESEROS" ("USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table MESEROS
--------------------------------------------------------

  ALTER TABLE "CHEDYS"."MESEROS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "CHEDYS"."MESEROS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "CHEDYS"."MESEROS" MODIFY ("PATERNO" NOT NULL ENABLE);
  ALTER TABLE "CHEDYS"."MESEROS" MODIFY ("RFC" NOT NULL ENABLE);
  ALTER TABLE "CHEDYS"."MESEROS" MODIFY ("TELEFONO" NOT NULL ENABLE);
  ALTER TABLE "CHEDYS"."MESEROS" MODIFY ("USUARIO" NOT NULL ENABLE);
  ALTER TABLE "CHEDYS"."MESEROS" MODIFY ("CONTRASENA" NOT NULL ENABLE);
  ALTER TABLE "CHEDYS"."MESEROS" ADD CHECK (edad BETWEEN 18 AND 75) ENABLE;
  ALTER TABLE "CHEDYS"."MESEROS" ADD CHECK (sexo IN ('Masculino', 'Femenino')) ENABLE;
  ALTER TABLE "CHEDYS"."MESEROS" ADD CHECK (rol IN ('Mesero', 'Gerente')) ENABLE;
  ALTER TABLE "CHEDYS"."MESEROS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CHEDYS"."MESEROS" ADD UNIQUE ("RFC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CHEDYS"."MESEROS" ADD UNIQUE ("USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
